version: "3"

networks:
  netradio.net:
    driver: bridge

services:
  front.radio:
    container_name: front.radio
    image: node
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ./frontend/node_modules:/usr/src/outside/frontend/node_modules
      - ./frontend/backend:/usr/src/app/frontend/backend
      - ./frontend/backend/node_modules:/usr/src/outside/frontend/node_modules
    working_dir: /usr/src/app/frontend
    command: 
      - bash -c 'npm i && npm start'
      - bash -c 'cd backend && npm i && npm run start'
    networks:
      - netradio.net

  # back.radio:
  #   container_name: back.radio
  #   image: node
  #   ports:
  #     - "19080:19080"
  #   volumes:
  #     - ./backend:/usr/src/app/backend
  #     - ./backend/node_modules:/usr/src/outside/backend/node_modules
  #   working_dir: /usr/src/app/backend
  #   command: bash -c 'npm i && npm run start'
  #   networks:
  #     - netradio.net
    
  # mysql.radio:
  #   container_name: mysql.radio
  #   image: mariadb:latest
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
  #   env_file:
  #     - ./backend/mysql/.env.dev
  #   ports: 
  #     - "3307:3306"
  #   volumes:
  #     - ./backend/mysql_data:/var/lib/mysql
  #   networks:
  #     - netradio.net
      
  # phpmyadmin.radio:
  #   container_name: phpmyadmin.radio
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment: 
  #     - PMA_ARBITRARY=1
  #   links:
  #     - mysql.radio
  #   networks:
  #     - netradio.net



 
